name: "Greet With A Random Joke"
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    name: setup environment
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: mast joke mara
        uses: deep5050/MastJokeMara@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          PR_msg: |
            Hi, {{author}},
            Thanks for opening an PR your PR will be mergerd soon if it doesn't has any conflist make sure you followed our Contributing guidlines in file.	
            	
            We will investigate :eyes:  and get back to you as soon as possible :+1: . Just make sure you have responed according to any of the prior issues.	
            	
            By that time enjoy this joke :point_down: , hope you like it :smile:	
            {{joke}}
